### ISSUE TITLE
Missing a LICENSE or COPYING file

### ISSUE THREAD

**Issue by nocnokneo** [dbzhang800/QtOpenCV#1]
The project should contain a LICENSE or COPYING file that clearly states the licensing terms that the software is distributed under.

**Comment by wolframteetz** [comment]
Added

**Comment by dbzhang800** [comment]
Hi, the software is licensed under MIT, you can find information in  the sources files.

**Comment by nocnokneo** [comment]
Including the license in the header of each source file is important so that each file can stand alone with licensing information but _only_ including the license in source files makes licensing unclear for users (since they'd then have to check _every_ source file to know what that all of OpenCV is licensed under the MIT license) and makes life more difficult for RPM/DEB packagers like myself. Basically all stakeholders who need to clearly know the license terms of given piece of software. It's also a de factor standard to include a LICENSE or COPYING file. See ["How to Apply a License to Your Software"](http://producingoss.com/en/license-quickstart.html).
